import Head from "next/head";


import JSONEditorComponent from "~@/editor";


export default function Home() {


  return (
    <div style={{ height: "100vh" }}>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <JSONEditorComponent />
    </div>
  );
}



