import Head from "next/head";

import { api } from "~@/utils/api";
import JSONEditorComponent from "~@/editor";


export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <div style={{ height: "100vh" }}>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <JSONEditorComponent />
    </div>
  );
}



